django_app/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include('post.urls'))
]
urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

django_app/post/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

from post import views

app_name = 'post'  # reverse 하는 모든 namespace URL에 앱네임을 지정해줘야 한다.(redirect할때 주의) 단 render함수는 제외
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<post_pk>\d+)/modify/$', views.post_modify, name='post_modify'),
    url(r'^(?P<post_pk>\d+)/delete/$', views.post_delete, name='post_delete'),

]

django_app/member/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    name = models.CharField(max_length=30)

django_app/post/models.py
"""
member application생성
    User모델 구현
        username, nickname
이후 해당 User모델을 Post나 Comment에서 author나 user항목으로 참조
"""
from django.db import models

# from django.contrib.auth.models import User
from django.conf import settings


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    photo = models.ImageField(upload_to='post', blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now_add=True)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='like_posts',
        through='PostLike',
    )
    tags = models.ManyToManyField(
        'Tag',
        blank=True
    )

    def add_comment(self, user, content):
        return self.comment_set.create(
            author=user,
            content=content,
        )

    def add_tag(self, tag_name):
        tag, tag_created = Tag.objects.get_or_create(name=tag_name)
        if not self.tags.filter(name=tag_name).exists():
            self.tags.add(tag)
        return

    @property
    def like_count(self):
        return self.like_users.count()

    def __str__(self):
        return '{} / {}'.format(self.author, self.created_date)


class PostLike(models.Model):
    post = models.ForeignKey(Post)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    created_date = models.DateTimeField(auto_now_add=True)

    # class Meta:
    #     db_table = 'post_post_like_users'


class Comment(models.Model):
    post = models.ForeignKey(Post)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now_add=True)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='CommentLike',
        related_name='like_comments'
    )

    def __str__(self):
        return '{}/{}'.format(self.post, self.author)


class CommentLike(models.Model):
    comment = models.ForeignKey(Comment)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    created_date = models.DateTimeField(auto_now_add=True)


# class PostLike(models.Model):
#     pass


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return 'Tag ({})'.format(self.name)

django_app/post/forms.py
from django import forms


class PostCreate(forms.Form):
    photo = forms.ImageField()


class PostModify(forms.Form):
    photo = forms.ImageField()

django_app/member/views.py
from django.shortcuts import render

# Create your views here.

django_app/post/views.py
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader

from member.models import User
from .forms import PostCreate, PostModify
from .models import Post

# 자동으로 Django에서 인증에 사용하는 User모데를래스를 리턴
User = get_user_model()

def post_list(request):
    # 모든 Post목록을 'posts'라는 key로 context에 담아 return render처리
    # post/post_list.html을 template으로 사용하도록 한다

    # 각 포스트에 대해 최대 4개까지의 댓글을 보여주도록 템플릿에 설정
    posts = Post.objects.all()

    context = {
        'posts': posts,
    }
    return render(request, 'post/post_list.html', context)


def post_detail(request, post_pk):
    # post_pk에 해당하는 Post객체를 리턴, 보여줌
    post = get_object_or_404(Post, pk=post_pk)
    # 구식 방식
    # template = loader.get_template('post/post_detail.html')
    # context = {
    #     'post': post,
    # }
    # rendering_string = template.render(context=context, request=request)
    # return HttpResponse(rendering_string)
    context = {
        'post': post
    }
    return render(request, 'post/post_detail.html', context)


def post_create(request):
    # POST요청을 받아 Post객체를 생성 후 post_list페이지로 redirect
    # if request.method == 'GET':
    #     form = PostCreate()
    #     context = {
    #         'form': form,
    #     }
    #     return render(request, 'post/post_create.html', context)
    # elif request.method == 'POST':
    #     form = PostCreate(request.POST, request.FILES)
    #     if form.is_valid():
    #         author = User.objects.first()
    #         photo = request.FILES['photo']
    #         Post.objects.create(
    #             author=author,
    #             photo=photo,
    #         )
    #         return redirect('post:post_list')
    #
    # else:
    #     form = PostCreate()
    #     context = {
    #         'form': form,
    #     }
    #     return render(request, 'post/post_create.html', context)
    if request.method == 'POST':
        user = User.objects.first()
        post = Post.objects.create(
            author=user,
            photo=request.FILES['file']
        )
        comment_string = request.POST.get('comment', '')

        if comment_string:
            post.comment_set.create(
                author=user,
                content=comment_string,
            )
        return redirect('post:post_detail', post_pk=post.pk)
    else:

        return render(request, 'post/post_create.html')




def post_modify(request, post_pk):
    post = Post.objects.get(pk=post_pk)

    if request.method == 'GET':
        form = PostModify()
        context = {
            'post': post,
            'forms': form,
        }
        return render(request, 'post/post_modify.html', context)
    elif request.method == 'POST':
        form = PostModify(request.POST, request.FILES)
        if form.is_valid():
            photo = request.FILES["photo"]
            post.photo = photo
            post.save()
            return redirect('post_detail', post_pk=post.pk)


def post_delete(request, post_pk):
    # post_pk에 해당하는 Post에 대한 delete요청만을 받음
    # 처리완료후에는 post_list페이지로 redirect
    post = Post.objects.get(pk=post_pk)
    if request.method == 'POST':
        post.delete()
        return redirect('post:post_list')

    elif request.method == 'GET':
        return redirect('post:post_detail', post_pk=post.pk)


def comment_create(request, post_pk):
    # POST요청을 받아 Comment객체를 생성 후 post_detail페이지로 redirect
    pass


def comment_modify(request, post_pk):
    # 수정
    pass


def comment_delete(request, post_pk, comment_pk):
    # POST요청을 받아 Comment객체를 delete, 이후 post_detail페이지로 redirect
    pass

django_app/templates/base/base.html
{% load staticfiles %}
<!doctype html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
  content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="{% static 'css/nomalize.css'%}">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <link rel="stylesheet" href="{% static 'css/post.css'%}">
  <title>Instagram</title>
</head>

<body>
  <div id="wrap">
    <header class="top-header">
      <nav>
        <div class="nav-left nav-item">
          <a href="#">
            <img src="{% static 'images/logo.png' %}" alt="">
          </a>
        </div>
        <div class="nav-center nav-item">
          <input type="text" placeholder="검색">
        </div>
        <div class="nav-right nav-item">
          <a href="#">
            <img src="{% static 'images/icon_explore.png' %}" alt="">
          </a>
          <a href="#">
            <img src="{% static 'images/icon_heart.png' %}" alt="">
          </a>
          <a href="#">
            <img src="{% static 'images/icon_profile.png' %}" alt="">
          </a>
        </div>
      </nav>
    </header>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </div>


</body>
</html>

django_app/templates/include/post.html
<article>
    <header>
        <div class="post-header-left">
            <img src="" alt="">
            <span>{{ post.author }}</span>
        </div>
        <div class="post-header-right">

        </div>
    </header>
    <div class="photo-container">
        <img src="{{ post.photo.url }}" alt="">
    </div>
    <div class="post-btn-container">
        <a href="#">
            <img src="" alt="">
        </a>
        <a href="#">
            <img src="" alt="">
        </a>
    </div>
    <p>좋아요 {{ post.like_count }}개</p>
    <div class="post-comment-container">
        {% for comment in post.comment_set.all|slice:'4' %}

            <div class="post-comment">
            <a href="" class="comment-author">{{ comment.author }}</a>
            <span class="comment-content">{{ comment.content }}</span>
            <a href="" class="comment-tag"></a>
        {% endfor %}
        </div>
    </div>
    <p class="created">{{ post.created_date }}</p>
    <form action="">
        <input type="text" placeholder="댓글달기">
    </form>
</article>

django_app/templates/post/post_create.html
{% extends 'base/base.html' %}

{% block content %}
    <div>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="file">
            <input type="text" name="comment" placeholder="댓글">
            <button type="submit">등록</button>
        </form>
    </div>
{% endblock %}

django_app/templates/post/post_detail.html
{% extends 'base/base.html' %}

{% block content %}

    {% include 'include/post.html' %}

{% endblock %}

django_app/templates/post/post_list.html
{% extends 'base/base.html' %}

{% block content %}
    {% for post in posts %}
        {% include 'include/post.html' %}
    {% endfor %}
{% endblock %}

django_app/templates/post/post_modify.html
{% extends 'base/base.html' %}

{% block content %}
    <form action="{% url 'post:post_modify' post_pk=post.id%}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% for form in forms %}
        {{ form }}
        {% endfor %}
        <button class="btn" type="submit">수정</button>
    </form>
{% endblock %}